on: [push]

jobs:
  merge_conflict_job:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      - uses: actions/checkout@v1
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v1.2
